steps:
  # Step 1: Debugging - List all files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking workspace files..."
        ls -R /workspace

  # Step 2: Build Docker image using blue/ as the context
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA', '-f', 'amazingapp/blue/Dockerfile', 'amazingapp/blue']

  # Step 3: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'amazingapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA

logsBucket: "gs://shaiksaleemafroz-logs"
