steps:
  # Step 1: Debugging - List all files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking workspace files..."
        ls -R /workspace

  # Step 2: Authenticate Docker with Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-docker.pkg.dev']

  # Step 3: Build Docker image using blue/ as the context
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA',
      '-f', 'amazingapp/blue/Dockerfile',
      'amazingapp/blue'
    ]

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'amazingapp'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - us-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA

logsBucket: "gs://shaiksaleemafroz-logs"
